name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    name: asdf-temporalite on ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system packages on macOS
        if: ${{ runner.os == 'macOS' }}
        run: brew install coreutils

      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: temporalite --version